async function deleteMessage(messageId) {

  
	try {
	  const response = await api.delete(`/notes/${messageId}`)
  
	  if (response.status === 200) {
		alert('Recado exclu√≠do com sucesso')
	  }
  
	} catch (error) {
	  console.log('Erro ao excluir recado', error)
	}
  }